(in-package #:sdl3-mixer-examples)

(defun music ()
  (with-init (:everything)
    (sdl3-mixer:init)
    (let ((mixer (sdl3-mixer:create-mixer-device)))
      (with-window (my-window :title "Mixer Example"
                              :w 200
                              :h 200)
        (with-renderer (my-renderer my-window)
          (flet ((clear-renderer (renderer)
                   (set-render-draw-color renderer 0 0 0 255)
                   (render-clear renderer)))
            (let* ((current-volume 1.0)
                   (music-path (asdf:system-relative-pathname 'sdl3-mixer-examples "examples/example_song.ogg"))
                   (music (sdl3-mixer:load-audio mixer music-path))
                   (music-track (sdl3-mixer:create-track mixer))
                   (volume-increment 0.1))

              ;; Set the the audio for the track
              (sdl3-mixer:set-track-audio music-track music)

              (with-event-loop (:method :poll)
                (:key-down (:scancode scancode)
			   (cond ((scancode= scancode :space)
				  (format t "Playing Song~%")
				  (sdl3-mixer:play-track music-track 1))
			         ((scancode= scancode :up)
				  (when (< (+ current-volume volume-increment) 1.8)
				    (incf current-volume volume-increment)
				    (format t "Current Volume: ~a~%" current-volume)
                                    (sdl3-mixer:set-track-gain music-track current-volume)))
			         ((scancode= scancode :down)
				  (when (> (- current-volume volume-increment) 0)
				    (decf current-volume volume-increment)
				    (format t "Current Volume: ~a~%" current-volume)
                                    (sdl3-mixer:set-track-gain music-track current-volume)))
			         ((scancode= scancode :escape)
				  (sdl3:push-event :quit))))
                (:idle ()
                       (clear-renderer my-renderer)
                       (render-present my-renderer))
                (:quit ()
                       (sdl3-mixer:quit)
                       t)))))))))
